### ISSUE TITLE
Are you planning to go any further with this?

### ISSUE THREAD

**Issue by timuckun** [RomanTurner/rephlex#1]
Your readme sounds really interesting. Just curious to see if you are planning on moving forward.

**Comment by RomanTurner** [comment]
Hey Tim,

I have been playing with it back and forth. I am halfway through a CLI for
the framework but doubt that it is even worth finishing. With the state of
ruby being dominated by rails and rails being controlled by a complete
douche, it doesn't make me want to continue coding in ruby even though I
have made some great friends in the community.

**Comment by timuckun** [comment]
Ok I guess.
